name: 04 - Using Actions

on:
    push:
        branches: [main]

jobs: 
    build: 
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: 04-using-actions/my-react-app  # in every command in run scope will be executed in specific working directory

        # Step 0 : checkout the code from the repository
        # Step1 : Install dependencies of our react project
        # Step 2 : Execute automated tests 

        steps: 
             #Step 0 : Clone the github project into runner
            - name: Checkout Code (Clone)
              uses: actions/checkout@v4

            - name: Printing Folders
              run: ls
            
            - name: Setup node
              uses: actions/setup-node@v4
              with: 
                node-version: '22.21.0'

            - name: Install react dependecies
              run: npm ci
              #working-directory: 04-using-actions/my-react-app
            
            - name: Run Unit tests
              run: npm run test

