name : 07 - Expressions

on :
    push:
    workflow_dispatch:
        inputs:
            debug: 
                description: "Enable debug mode"
                type: boolean
                default: false

jobs:
    echo: 
         runs-on: ubuntu-latest
         steps:
            - name: Print start-up data
              if: ${{inputs.debug}}
              run: |
                  echo "Triggered by : ${{github.event_name}}"
                  echo "Branch : ${{github.ref}}"
                  echo "Commit SHA : ${{github.sha}}"
                  echo "Runner OS : ${{runner.os}}"

            - name: Print when triggered by main branch
              if: ${{inputs.debug && github.ref == 'refs/heads/main'}}
              run: |
                 echo "I was triggered from main"

            - name: Greeting
              run: echo "Hello world!"
        
    
